### ISSUE TITLE
The music in the Tantegel Throne Room should be different from that of the Tantegel Courtyard

### ISSUE THREAD

**Issue by eforgacs** [bobbylight/DragonWarriorJS#1]
First off, huge fan of your work! I love the Dragon Warrior JavaScript adaptation.

A very minor issue - the music in the Tantegel Throne Room is slightly different from the Tantegel Courtyard. Should be an easy fix.

Thanks for making this!

**Comment by bobbylight** [comment]
Haha thanks! It's been so long since I've worked on this project, but it's always one I want to revisit. This comment might be just the motivation I need to revisit it!

**Comment by eforgacs** [comment]
Believe it or not, I'm working on a Python implementation of Dragon Warrior as well at the moment. Your JS version is a big inspiration for me!

**Comment by eforgacs** [comment]
By the way, I've only noticed this bug in the version that's uploaded on http://bobbylight.github.io/DragonWarriorJS/ . The actual code on the GitHub page appears to have fixed this in commit e0d662c15838563ac3d3d94e9b728401c5e142c4, "Proper music in Tantegel Castle. Make the demo page look a little more retro."

**Comment by bobbylight** [comment]
Sounds good.  I'm in the process of modernizing this project now.  It's more work than I thought.  I'm porting all the JS over to TypeScript and changing the build/dev environment from gulp to webpack.  Should be easier to attract PRs, besides webpack-dev-server being a much better dev environment for rapid development.  Once all that's done I'll update the demo game with the latest before starting work on new features.
